### ISSUE TITLE
Server crashes on launch

### ISSUE THREAD

**Issue by chandradeepdey** [FStarLang/fstar-vscode-assistant#5]
Hi, I am trying to open a directory with a very simple .fst file but the server crashes.

`.fst.config.json`
```json
{ "fstar_exe": "fstar.exe" }
```

`Main.fst`
```fstar
module Main

let incr (x:int) : int = x + 1
```

Here is the log corresponding to the last crash before VSCode stopped restarting the server -
```
[Info  - 22:04:11] Connection to server got closed. Server will restart.
/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/out/server.js:757
    fstarConfig.options.forEach((opt) => { options.push(opt); });
                        ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at refreshDocumentState (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/out/server.js:757:25)
    at onOpenHandler (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/out/server.js:792:11)
    at /home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/out/server.js:810:5
    at CallbackList.invoke (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at /home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-languageserver/lib/common/server.js:130:29
    at handleNotification (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:547:25)
    at processMessageQueue (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:289:17)
    at Immediate.<anonymous> (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at process.processImmediate (node:internal/timers:466:21)
[Info  - 22:04:11] Connection to server got closed. Server will restart.
/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/out/server.js:757
    fstarConfig.options.forEach((opt) => { options.push(opt); });
                        ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at refreshDocumentState (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/out/server.js:757:25)
    at onOpenHandler (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/out/server.js:792:11)
    at /home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/out/server.js:810:5
    at CallbackList.invoke (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at /home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-languageserver/lib/common/server.js:130:29
    at handleNotification (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:547:25)
    at processMessageQueue (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:289:17)
    at Immediate.<anonymous> (/home/chandradeep/.vscode/extensions/fstarlang.fstar-vscode-assistant-0.2.0/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at process.processImmediate (node:internal/timers:466:21)
[Error - 22:04:11] Connection to server got closed. Server will not be restarted.
```

`fstar.exe --version`
```
F* 2023.03.22~dev
platform=Linux_x86_64
compiler=OCaml 4.13.1
date=2023-03-29 13:43:00 -0300
commit=3cb6386009297ebc0f3a287cff62082320b765b4
```

**Comment by nikswamy** [comment]
Thanks! Will fix

**Comment by chandradeepdey** [comment]
Thank you.
